config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "libraries/create"
  devise_for :users,
             controllers: {
               sessions: "users/sessions",
               registrations: "users/registrations"
             }

  resources :books do
    resources :comments, only: [:create]
    post "add_to_library", to: "libraries#create"
  end

  resources :authors
  resources :users, only: %i[show update destroy]

  namespace :settings do
    get "profile", to: "user_settings#show_profile"
    get "account", to: "user_settings#show_account"
    get "appearance", to: "user_settings#show_appearance"
    get "notifications", to: "user_settings#show_notifications"
    get "emails", to: "user_settings#show_emails"
    get "password", to: "user_settings#show_password"
  end

  mount Lookbook::Engine, at: "/lookbook" if Rails.env.development?

  root "pages#index"
end

app/models/author.rb
class Author < ApplicationRecord
  # relations
  has_many :books
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[show edit update destroy]

  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def edit
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def update
  end

  def destroy
  end

  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: "Книга была успешно создана." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:name, :description, :birth_on) # замените на реальные параметры вашей модели
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
  end
end

app/views/authors/index.html.erb
<div class="container mt-6 px-4 mx-auto">
  <div class="flex flex-wrap">
    <div class="basis-1/4">
      <%= link_to "Добавить нового автора", new_author_path, class: "focus:outline-none" %>
    </div>
    <div class="basis-3/4">
      <div class="flex flex-wrap ">
        <% @authors.each do |author| %>
          <div class="focus:outline-none h-48 w-40 mb-12 mr-4">
            <%= link_to author_path(author) do %>
              <img
                src="https://tuk-cdn.s3.amazonaws.com/assets/components/avatars/a_7_7.png"
                alt="man avatar"
                class="h-full w-full rounded overflow-hidden shadow"
              />
              <div class="flex items-center justify-between">
                <h2 tabindex="0" class="focus:outline-none font-semibold ">
                  <%= author.name %>
                </h2>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/authors/new.html.erb
<h1>Добавить нового автора</h1>

<%= simple_form_for @author do |form| %>
  <%= form.input :name %>
  <%= form.input :description %>
  <%= form.submit "Создать автора" %>
<% end %>

app/views/authors/show.html.erb
<%= @author.name %>

<p><%= @author.description %></p>