config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "libraries/create"
  devise_for :users,
             controllers: {
               sessions: "users/sessions",
               registrations: "users/registrations"
             }

  resources :books do
    resources :comments, only: [:create]
    post "add_to_library", to: "libraries#create"
  end

  resources :authors
  resources :users, only: %i[show update destroy]

  namespace :settings do
    get "profile", to: "user_settings#show_profile"
    get "account", to: "user_settings#show_account"
    get "appearance", to: "user_settings#show_appearance"
    get "notifications", to: "user_settings#show_notifications"
    get "emails", to: "user_settings#show_emails"
    get "password", to: "user_settings#show_password"
  end

  mount Lookbook::Engine, at: "/lookbook" if Rails.env.development?

  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  # relations
  has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  MAX_RATING = 5

  has_one_attached :poster
  has_many :comments, dependent: :destroy
  belongs_to :author
  # belongs_to :user

  validates :title, :author_id, presence: true
  validates :rating, numericality: { in: 0..MAX_RATING }

  def author_name
    author.name
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :text, presence: true
end

app/models/library.rb
class Library < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :user_id, presence: true
  validates :book_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_one_attached :avatar
  has_one_attached :background

  has_many :comments, dependent: :destroy
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[show edit update destroy]

  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def edit
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def update
  end

  def destroy
  end

  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: "Книга была успешно создана." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:name, :description, :birth_on) # замените на реальные параметры вашей модели
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
    @authors = Author.all
  end

  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Книга была успешно создана." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @comments = @book.comments
    @comment = Comment.new
  end

  def edit
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Книга была успешно обновлена." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html do
        redirect_to books_url, notice: "Книга была успешно удалена."
      end
      format.json { head :no_content }
    end
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author_id, :description, :poster)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_book

  def create
    @comment = @book.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @book, notice: "Комментарий был успешно добавлен."
    else
      error_message = @comment.errors.full_messages.join(", ")
      redirect_to @book,
                  alert: "Ошибка при добавлении комментария: #{error_message}"
    end
  end

  private

  def set_book
    @book = Book.find(params[:book_id])
  end

  def comment_params
    params.require(:comment).permit(:text, :book_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/turbo_controller.rb
class TurboController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      if get?
        raise e
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update]
  before_action :authenticate_user!

  def show
  end

  def edit
  end

  # rubocop:disable Metrics/MethodLength
  # rubocop:disable Metrics/AbcSize
  def update
    if @user.update(user_params)
      flash.now[:success] = t(:label_update_settings_suсcess)
      render_turbo_stream_with_flash

      respond_to do |format|
        format.html { redirect_to settings_profile_path }
        format.turbo_stream
      end
    else
      flash.now[:error] = t(:label_update_settings_failed)
      render_turbo_stream_with_flash
    end
  end

  # rubocop:enable Metrics/MethodLength
  # rubocop:enable Metrics/AbcSize
  def destroy
    @user = User.find(current_user.id)
    if @user.destroy
      redirect_to root_path, notice: "Ваш аккаунт успешно удален."
    else
      redirect_to settings_account_path,
                  alert: "Произошла ошибка при удалении аккаунта."
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :email,
      :password,
      :password_confirmation,
      :username,
      :avatar,
      :background,
      :first_name,
      :last_name
    )
  end
end

app/helpers/after_signup_helper.rb
module AfterSignupHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def star_rating_class(book, index)
    if index < book.rating
      "fill-yellow-400 stroke-yellow-400"
    else
      "fill-transparent stroke-gray-400"
    end
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/_flash.html.erb
<div class="space-y-4" id="flash">
  <% flash.each do |type, message| %>
    <%= render "common/flash_body", type: type, message: message %>
  <% end %>
</div>

app/views/common/_flash_body.html.erb
<% case type.to_sym %>
<% when :success %>
  <% title = t("flash_messages.success") %>
<% when :alert %>
  <% title = t("flash_messages.alert") %>
<% when :warning %>
  <% title = t("flash_messages.warning") %>
<% else %>
  <% title = t("flash_messages.default") %>
<% end %>

<div
  data-controller="flash"
  aria-live="assertive"
  class="z-10 pointer-events-none fixed inset-0 flex items-end px-4 py-6 sm:items-start sm:p-6"
>
  <div class="flex w-full flex-col items-center space-y-4 sm:items-end">
    <div
      class="pointer-events-auto w-full max-w-sm overflow-hidden rounded-lg bg-white shadow-lg ring-1 ring-black ring-opacity-5"
    >
      <div class="p-4">
        <div class="flex items-start">
          <div class="flex-shrink-0">
            <%= render "common/flash_icon", type: type.to_sym %>
          </div>
          <div class="ml-3 w-0 flex-1 pt-0.5">
            <p class="text-sm font-medium text-gray-900"><%= title %></p>
            <p class="mt-1 text-sm text-gray-500"><%= message %></p>
          </div>
          <div class="ml-4 flex flex-shrink-0">
            <button
              data-action="flash#dismiss"
              type="button"
              class="inline-flex rounded-md bg-white text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
            >
              <span class="sr-only">Close</span>
              <svg
                class="h-5 w-5"
                viewBox="0 0 20 20"
                fill="currentColor"
                aria-hidden="true"
              >
                <path
                  d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z"
                />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/common/_flash_icon.html.erb
<% case type %>
<% when :success %>
  <svg
    class="h-6 w-6 text-green-400"
    fill="none"
    viewBox="0 0 24 24"
    stroke-width="1.5"
    stroke="currentColor"
    aria-hidden="true"
  >
    <path
      stroke-linecap="round"
      stroke-linejoin="round"
      d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
    />
  </svg>
<% when :alert %>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 20 20"
    fill="currentColor"
    class="text-red-400 h-6 w-6"
  >
    <path
      fill-rule="evenodd"
      d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.28 7.22a.75.75 0 00-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 101.06 1.06L10 11.06l1.72 1.72a.75.75 0 101.06-1.06L11.06 10l1.72-1.72a.75.75 0 00-1.06-1.06L10 8.94 8.28 7.22z"
      clip-rule="evenodd"
    ></path>
  </svg>
<% when :warning %>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 20 20"
    fill="currentColor"
    class="h-6 w-6"
  >
    <path
      fill-rule="evenodd"
      d="M8.485 2.495c.673-1.167 2.357-1.167 3.03 0l6.28 10.875c.673 1.167-.17 2.625-1.516 2.625H3.72c-1.347 0-2.189-1.458-1.515-2.625L8.485 2.495zM10 5a.75.75 0 01.75.75v3.5a.75.75 0 01-1.5 0v-3.5A.75.75 0 0110 5zm0 9a1 1 0 100-2 1 1 0 000 2z"
      clip-rule="evenodd"
    ></path>
  </svg>
<% else %>
  <!-- Дефолтный SVG -->
<% end %>

app/views/layouts/_main.html.erb
<div
  class="hidden fixed left-0 w-full h-full transition-opacity duration-300 mt-header z-[5]"
></div>
<div
  class="relative flex min-h-svh flex-1 flex-col peer-data-[variant=inset]:min-h-[calc(100svh-theme(spacing.4))] md:peer-data-[variant=inset]:m-2 md:peer-data-[state=collapsed]:peer-data-[variant=inset]:ml-2 md:peer-data-[variant=inset]:ml-0 md:peer-data-[variant=inset]:rounded-xl md:peer-data-[variant=inset]:shadow"
>
  <%= render partial: 'layouts/header/header', locals: { user: current_user } %>
  <div class="flex flex-1 flex-col gap-4 p-4 pt-0">
    <%= yield %>
  </div>
  <%# Невидимая кнопка для работы расфокуса DropdownComponent по ESC %>
  <button type="button" id="dropdown-close-helper" class="size-0"></button>
</div>

app/views/layouts/_top_menu.html.erb
<div class="navbar bg-gray-50 border border-gray-100">
  <div class="navbar-start">
    <div class="dropdown">
      <label tabindex="0" class="btn btn-ghost btn-circle">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-5 w-5"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M4 6h16M4 12h16M4 18h7"
          />
        </svg>
      </label>
      <ul
        tabindex="0"
        class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52"
      >
        <li><%= link_to "Директория", books_path %></li>
        <li><%= link_to "Авторы", authors_path %></li>
        <li><%= link_to "Рекомендатор", root_path %></li>
      </ul>
    </div>
  </div>
  <div class="navbar-center">
    <%= link_to root_path, class: "btn btn-ghost normal-case text-xl" do %>
      <%= image_tag "logo.png", class: "w-14 h-14 " %>
      LIB.DIRECTORY
    <% end %>
  </div>
  <div class="navbar-end">
    <button class="btn btn-ghost btn-circle">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class="h-5 w-5"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
        />
      </svg>
    </button>
    <button class="btn btn-ghost btn-circle">
      <div class="indicator">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-5 w-5"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"
          />
        </svg>
      </div>
    </button>

    <div class="dropdown dropdown-end">
      <label tabindex="0" class="btn btn-ghost btn-circle avatar">
        <div class="w-10 rounded-full">
          <% if current_user&.avatar&.attached? %>
            <%= image_tag current_user.avatar %>
          <% else %>
            <span
              class="inline-flex h-10 w-10 items-center justify-center rounded-full bg-gray-500"
            >
              <span class="font-medium leading-none text-white">A</span>
            </span>
          <% end %>
        </div>
      </label>
      <ul
        tabindex="0"
        class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52 z-10"
      >
        <% if user_signed_in? %>
          <li><%= link_to (t :label_profile), current_user %></li>
          <li><%= link_to (t :label_settings), settings_profile_path %></li>
          <li>
            <%= link_to (t :label_exit),
                        destroy_user_session_path,
                        data: {
                          turbo_method: :delete,
                        } %>
          </li>
        <% else %>
          <li><%= link_to (t :label_sign_up), new_user_registration_path %></li>
          <li><%= link_to (t :label_sign_in), user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="light" class="text-xs md:text-sm lg:text-base">
<head>
  <title><%= t("app.name") %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= vite_client_tag %>
  <%= vite_javascript_tag "application" %>
</head>

<body>
<%= render partial: "common/flash" %>
  <div style="--sidebar-width:16rem;--sidebar-width-icon:3rem" class="group/sidebar-wrapper flex min-h-svh w-full has-[[data-variant=inset]]:bg-sidebar">
    <%= render partial: 'layouts/sidebar/sidemenu' %>
    <%= render partial: 'layouts/main' %>
    <div class="absolute flex w-full flex-col overflow-y-auto overflow-x-hidden pl-4 sidemenu_shadow"></div>
  </div>
</body>
</html>

app/views/layouts/header/_header.html.erb
<div
  class="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12"
>
  <div class="flex items-center gap-2 px-4">
    <button
      class="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 [&amp;_svg]:pointer-events-none [&amp;_svg]:size-4 [&amp;_svg]:shrink-0 hover:bg-accent hover:text-accent-foreground h-7 w-7 -ml-1"
      data-sidebar="trigger"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
        class="size-4 lucide lucide-panel-left "
      >
        <rect width="18" height="18" x="3" y="3" rx="2"></rect>
        <path d="M9 3v18"></path>
      </svg>
      <span class="sr-only"
      ><font style="vertical-align: inherit;"
      ><font style="vertical-align: inherit;"
      >Переключить боковую панель</font
      ></font
      ></span
      >
    </button>

    <div
      data-orientation="vertical"
      role="none"
      class="shrink-0 bg-neutral-300 w-[1px] mr-2 h-4"
    ></div>

    <% if current_page?(root_path) %>
      <%= render BreadcrumbsComponent.new(items: [
        { name: 'Главная', url: '/' },
      ]) %>
    <% else %>
      <%= render BreadcrumbsComponent.new %>
  <% end %>
  </div>
</div>

app/views/layouts/sidebar/_header.html.erb
<div data-sidebar="header" class="flex flex-col gap-2 p-2">
  <ul data-sidebar="menu" class="flex w-full min-w-0 flex-col gap-1">
    <li data-sidebar="menu-item" class="relative group/menu-item">
      <%= link_to root_path, class: "peer/menu-button flex w-full items-center gap-2 overflow-hidden rounded-md p-2 text-left outline-none transition-[width,height,padding] focus-visible:ring-2 active:bg-neutral-200 active:text-sidebar-accent-foreground disabled:pointer-events-none disabled:opacity-50 group-has-[[data-sidebar=menu-action]]/menu-item:pr-8 aria-disabled:pointer-events-none aria-disabled:opacity-50 data-[active=true]:bg-sidebar-accent data-[active=true]:font-medium data-[active=true]:text-sidebar-accent-foreground data-[state=open]:hover:bg-sidebar-accent data-[state=open]:hover:text-sidebar-accent-foreground group-data-[collapsible=icon]:!size-8 [&amp;>span:last-child]:truncate [&amp;>svg]:size-4 [&amp;>svg]:shrink-0 hover:bg-gray-100 hover:text-sidebar-accent-foreground h-12 text-sm group-data-[collapsible=icon]:!p-0 data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground" do %>
        <div
          class="flex aspect-square items-center justify-center rounded-lg bg-black text-white size-8"
        >
          D
        </div>
        <div class="grid flex-1 text-left text-sm leading-tight">
                <span class="truncate font-semibold">LIB</span
                ><span class="truncate text-xs">DIRECTORY</span>
        </div>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
          class="ml-auto size-4 lucide lucide-chevrons-up-down"
        >
          <path d="m7 15 5 5 5-5"></path>
          <path d="m7 9 5-5 5 5"></path>
        </svg>
      <% end %>
    </li>
  </ul>
</div>

app/views/layouts/sidebar/_sidemenu.html.erb
<div
  class="z-50 hidden group peer text-sidebar-foreground md:block"
  data-state="expanded"
  data-collapsible=""
  data-variant="sidebar"
  data-side="left"
>
  <div
    class="duration-200 relative h-svh w-[--sidebar-width] bg-transparent transition-[width] ease-linear group-data-[collapsible=offcanvas]:w-0 group-data-[side=right]:rotate-180 group-data-[collapsible=icon]:w-[--sidebar-width-icon]"
  ></div>
  <div
    class="duration-200 bg-neutral-50 fixed inset-y-0 z-10 hidden h-svh w-[--sidebar-width] transition-[left,right,width] ease-linear md:flex left-0 group-data-[collapsible=offcanvas]:left-[calc(var(--sidebar-width)*-1)] group-data-[collapsible=icon]:w-[--sidebar-width-icon] group-data-[side=left]:border-r group-data-[side=right]:border-l"
  >
    <div
      data-sidebar="sidebar"
      class="flex h-full w-full flex-col bg-sidebar group-data-[variant=floating]:rounded-lg group-data-[variant=floating]:border group-data-[variant=floating]:border-sidebar-border group-data-[variant=floating]:shadow"
    >
      <%# Блок брендирования приложения %>
      <%= render partial: "layouts/sidebar/header" %>

      <%# Блок с группами основных объектов приложения %>
      <%= render partial: "layouts/sidebar/content" %>

      <div data-sidebar="footer" class="flex flex-col gap-2 p-2">
        <ul data-sidebar="menu" class="flex w-full min-w-0 flex-col gap-1">
          <li data-sidebar="menu-item" class="relative group/menu-item">
            <button
              data-sidebar="menu-button"
              data-size="lg"
              data-active="false"
              class="peer/menu-button flex w-full items-center gap-2 overflow-hidden rounded-md p-2 text-left outline-none ring-sidebar-ring transition-[width,height,padding] focus-visible:ring-2 active:bg-sidebar-accent active:text-sidebar-accent-foreground disabled:pointer-events-none disabled:opacity-50 group-has-[[data-sidebar=menu-action]]/menu-item:pr-8 aria-disabled:pointer-events-none aria-disabled:opacity-50 data-[active=true]:bg-sidebar-accent data-[active=true]:font-medium data-[active=true]:text-sidebar-accent-foreground data-[state=open]:hover:bg-sidebar-accent data-[state=open]:hover:text-sidebar-accent-foreground group-data-[collapsible=icon]:!size-8 [&amp;>span:last-child]:truncate [&amp;>svg]:size-4 [&amp;>svg]:shrink-0 hover:bg-sidebar-accent hover:text-sidebar-accent-foreground h-12 text-sm group-data-[collapsible=icon]:!p-0 data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
              type="button"
              id="radix-:Rspuuuuuu6ja:"
              aria-haspopup="menu"
              aria-expanded="false"
              data-state="closed"
            >
              <span
                class="relative flex h-8 w-8 shrink-0 overflow-hidden rounded-lg"
              ><img
                class="aspect-square h-full w-full"
                alt="shadcn"
                src="https://ui.shadcn.com/avatars/shadcn.jpg"
                /></span>
              <div class="grid flex-1 text-left text-sm leading-tight">
                <span class="truncate font-semibold">Anonim User</span
                ><span class="truncate text-xs">m@example.com</span>
              </div>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="ml-auto lucide lucide-chevrons-up-down size-4"
              >
                <path d="m7 15 5 5 5-5"></path>
                <path d="m7 9 5-5 5 5"></path>
              </svg>
            </button>
          </li>
        </ul>
      </div>
      <button
        data-sidebar="rail"
        aria-label="Toggle Sidebar"
        tabindex="-1"
        title="Toggle Sidebar"
        class="absolute inset-y-0 z-20 hidden w-4 -translate-x-1/2 transition-all ease-linear after:absolute after:inset-y-0 after:left-1/2 after:w-[2px] hover:after:bg-sidebar-border group-data-[side=left]:-right-4 group-data-[side=right]:left-0 sm:flex [[data-side=left]_&amp;]:cursor-w-resize [[data-side=right]_&amp;]:cursor-e-resize [[data-side=left][data-state=collapsed]_&amp;]:cursor-e-resize [[data-side=right][data-state=collapsed]_&amp;]:cursor-w-resize group-data-[collapsible=offcanvas]:translate-x-0 group-data-[collapsible=offcanvas]:after:left-full group-data-[collapsible=offcanvas]:hover:bg-sidebar [[data-side=left][data-collapsible=offcanvas]_&amp;]:-right-2 [[data-side=right][data-collapsible=offcanvas]_&amp;]:-left-2"
      ></button>
    </div>
  </div>
</div>